import type { Role } from '@/types/roles';

export type SalaryRole = Omit<Role, 'id' | 'created_at' | 'updated_at' | 'vetting_criteria'>;

export const SALARY_DATA: SalaryRole[] = [
  {
    slug: 'software-developer',
    title_en: 'Software Developer',
    title_es: 'Desarrollador de Software',
    category: 'technology',
    us_salary_min: 85000, us_salary_max: 160000, us_salary_avg: 120000,
    offshore_salary_min: 18000, offshore_salary_max: 42000, offshore_salary_avg: 30000,
    savings_percentage: 75,
    demand_level: 'critical',
    skills_required: ['JavaScript', 'Python', 'React', 'Node.js', 'SQL', 'Git'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'PK', 'BR', 'AR', 'RO', 'MA'],
    is_featured: true, sort_order: 1,
    description_en: 'Full-cycle software developers proficient in modern languages and frameworks.',
    description_es: 'Desarrolladores de software de ciclo completo, competentes en lenguajes y frameworks modernos.',
  },
  {
    slug: 'senior-software-engineer',
    title_en: 'Senior Software Engineer',
    title_es: 'Ingeniero de Software Senior',
    category: 'technology',
    us_salary_min: 120000, us_salary_max: 200000, us_salary_avg: 155000,
    offshore_salary_min: 30000, offshore_salary_max: 60000, offshore_salary_avg: 45000,
    savings_percentage: 71,
    demand_level: 'critical',
    skills_required: ['System Design', 'Architecture', 'Leadership', 'CI/CD', 'Cloud'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 2,
    description_en: 'Senior engineers with 5+ years of experience in system design and team leadership.',
    description_es: 'Ingenieros senior con 5+ años de experiencia en diseño de sistemas y liderazgo de equipos.',
  },
  {
    slug: 'full-stack-developer',
    title_en: 'Full Stack Developer',
    title_es: 'Desarrollador Full Stack',
    category: 'technology',
    us_salary_min: 90000, us_salary_max: 170000, us_salary_avg: 125000,
    offshore_salary_min: 20000, offshore_salary_max: 45000, offshore_salary_avg: 32000,
    savings_percentage: 74,
    demand_level: 'critical',
    skills_required: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'BR', 'AR', 'RO'],
    is_featured: true, sort_order: 3,
    description_en: 'Versatile developers handling both frontend and backend development.',
    description_es: 'Desarrolladores versátiles que manejan tanto el frontend como el backend.',
  },
  {
    slug: 'frontend-developer',
    title_en: 'Frontend Developer',
    title_es: 'Desarrollador Frontend',
    category: 'technology',
    us_salary_min: 80000, us_salary_max: 150000, us_salary_avg: 110000,
    offshore_salary_min: 16000, offshore_salary_max: 36000, offshore_salary_avg: 26000,
    savings_percentage: 76,
    demand_level: 'high',
    skills_required: ['React', 'TypeScript', 'CSS', 'Tailwind', 'Next.js'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 4,
    description_en: 'Specialists in building responsive, accessible user interfaces.',
    description_es: 'Especialistas en construir interfaces de usuario responsivas y accesibles.',
  },
  {
    slug: 'backend-developer',
    title_en: 'Backend Developer',
    title_es: 'Desarrollador Backend',
    category: 'technology',
    us_salary_min: 90000, us_salary_max: 165000, us_salary_avg: 125000,
    offshore_salary_min: 18000, offshore_salary_max: 40000, offshore_salary_avg: 30000,
    savings_percentage: 76,
    demand_level: 'high',
    skills_required: ['Node.js', 'Python', 'Java', 'PostgreSQL', 'Redis'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 5,
    description_en: 'Server-side engineers building scalable APIs and data systems.',
    description_es: 'Ingenieros de servidor que construyen APIs escalables y sistemas de datos.',
  },
  {
    slug: 'devops-engineer',
    title_en: 'DevOps Engineer',
    title_es: 'Ingeniero DevOps',
    category: 'technology',
    us_salary_min: 100000, us_salary_max: 180000, us_salary_avg: 140000,
    offshore_salary_min: 22000, offshore_salary_max: 48000, offshore_salary_avg: 35000,
    savings_percentage: 75,
    demand_level: 'high',
    skills_required: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR', 'RO', 'IN'],
    is_featured: true, sort_order: 6,
    description_en: 'Infrastructure and deployment automation specialists.',
    description_es: 'Especialistas en infraestructura y automatización de despliegue.',
  },
  {
    slug: 'data-engineer',
    title_en: 'Data Engineer',
    title_es: 'Ingeniero de Datos',
    category: 'data',
    us_salary_min: 95000, us_salary_max: 175000, us_salary_avg: 135000,
    offshore_salary_min: 20000, offshore_salary_max: 45000, offshore_salary_avg: 32000,
    savings_percentage: 76,
    demand_level: 'high',
    skills_required: ['Python', 'SQL', 'Spark', 'Airflow', 'dbt'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR', 'RO', 'IN'],
    is_featured: true, sort_order: 7,
    description_en: 'Build and maintain data pipelines and warehousing solutions.',
    description_es: 'Construyen y mantienen pipelines de datos y soluciones de almacenamiento.',
  },
  {
    slug: 'data-scientist',
    title_en: 'Data Scientist',
    title_es: 'Científico de Datos',
    category: 'data',
    us_salary_min: 100000, us_salary_max: 185000, us_salary_avg: 140000,
    offshore_salary_min: 22000, offshore_salary_max: 50000, offshore_salary_avg: 36000,
    savings_percentage: 74,
    demand_level: 'high',
    skills_required: ['Python', 'ML', 'Statistics', 'TensorFlow', 'SQL'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR', 'IN'],
    is_featured: false, sort_order: 8,
    description_en: 'Machine learning and statistical analysis experts.',
    description_es: 'Expertos en aprendizaje automático y análisis estadístico.',
  },
  {
    slug: 'qa-engineer',
    title_en: 'QA Engineer',
    title_es: 'Ingeniero QA',
    category: 'technology',
    us_salary_min: 70000, us_salary_max: 130000, us_salary_avg: 95000,
    offshore_salary_min: 14000, offshore_salary_max: 30000, offshore_salary_avg: 22000,
    savings_percentage: 77,
    demand_level: 'medium',
    skills_required: ['Selenium', 'Playwright', 'Jest', 'API Testing', 'CI/CD'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'PK', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 9,
    description_en: 'Quality assurance engineers ensuring software reliability.',
    description_es: 'Ingenieros de aseguramiento de calidad que garantizan la fiabilidad del software.',
  },
  {
    slug: 'mobile-developer',
    title_en: 'Mobile Developer',
    title_es: 'Desarrollador Móvil',
    category: 'technology',
    us_salary_min: 90000, us_salary_max: 165000, us_salary_avg: 125000,
    offshore_salary_min: 18000, offshore_salary_max: 42000, offshore_salary_avg: 30000,
    savings_percentage: 76,
    demand_level: 'high',
    skills_required: ['React Native', 'Swift', 'Kotlin', 'Flutter'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 10,
    description_en: 'iOS and Android app developers using native and cross-platform tools.',
    description_es: 'Desarrolladores de apps iOS y Android usando herramientas nativas y multiplataforma.',
  },
  {
    slug: 'ui-ux-designer',
    title_en: 'UI/UX Designer',
    title_es: 'Diseñador UI/UX',
    category: 'creative',
    us_salary_min: 75000, us_salary_max: 140000, us_salary_avg: 105000,
    offshore_salary_min: 14000, offshore_salary_max: 32000, offshore_salary_avg: 23000,
    savings_percentage: 78,
    demand_level: 'high',
    skills_required: ['Figma', 'Sketch', 'User Research', 'Prototyping', 'Design Systems'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'BR', 'AR', 'RO'],
    is_featured: true, sort_order: 11,
    description_en: 'User interface and experience designers creating intuitive products.',
    description_es: 'Diseñadores de interfaz y experiencia de usuario creando productos intuitivos.',
  },
  {
    slug: 'product-manager',
    title_en: 'Product Manager',
    title_es: 'Gerente de Producto',
    category: 'executive',
    us_salary_min: 100000, us_salary_max: 180000, us_salary_avg: 140000,
    offshore_salary_min: 24000, offshore_salary_max: 50000, offshore_salary_avg: 36000,
    savings_percentage: 74,
    demand_level: 'high',
    skills_required: ['Roadmapping', 'Agile', 'Analytics', 'Stakeholder Mgmt'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR'],
    is_featured: true, sort_order: 12,
    description_en: 'Strategic product leaders driving roadmap and team alignment.',
    description_es: 'Líderes estratégicos de producto que impulsan la hoja de ruta y alineación del equipo.',
  },
  {
    slug: 'project-manager',
    title_en: 'Project Manager',
    title_es: 'Gerente de Proyecto',
    category: 'operations',
    us_salary_min: 80000, us_salary_max: 140000, us_salary_avg: 105000,
    offshore_salary_min: 16000, offshore_salary_max: 35000, offshore_salary_avg: 25000,
    savings_percentage: 76,
    demand_level: 'medium',
    skills_required: ['Agile', 'Scrum', 'Jira', 'Risk Management', 'Budgeting'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 13,
    description_en: 'Experienced project managers keeping teams on track and on budget.',
    description_es: 'Gerentes de proyecto experimentados manteniendo equipos en tiempo y presupuesto.',
  },
  {
    slug: 'cybersecurity-analyst',
    title_en: 'Cybersecurity Analyst',
    title_es: 'Analista de Ciberseguridad',
    category: 'technology',
    us_salary_min: 85000, us_salary_max: 160000, us_salary_avg: 120000,
    offshore_salary_min: 18000, offshore_salary_max: 40000, offshore_salary_avg: 28000,
    savings_percentage: 77,
    demand_level: 'high',
    skills_required: ['SIEM', 'Penetration Testing', 'Compliance', 'Network Security'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR', 'RO', 'IN'],
    is_featured: false, sort_order: 14,
    description_en: 'Security professionals protecting systems and data.',
    description_es: 'Profesionales de seguridad protegiendo sistemas y datos.',
  },
  {
    slug: 'cloud-architect',
    title_en: 'Cloud Architect',
    title_es: 'Arquitecto Cloud',
    category: 'technology',
    us_salary_min: 130000, us_salary_max: 220000, us_salary_avg: 175000,
    offshore_salary_min: 30000, offshore_salary_max: 65000, offshore_salary_avg: 48000,
    savings_percentage: 73,
    demand_level: 'critical',
    skills_required: ['AWS', 'Azure', 'GCP', 'Terraform', 'Microservices'],
    countries_available: ['CO', 'MX', 'PL', 'UA', 'BR', 'AR', 'RO'],
    is_featured: false, sort_order: 15,
    description_en: 'Enterprise cloud infrastructure architects and migration specialists.',
    description_es: 'Arquitectos de infraestructura cloud empresarial y especialistas en migración.',
  },
  {
    slug: 'executive-assistant',
    title_en: 'Executive Assistant',
    title_es: 'Asistente Ejecutivo',
    category: 'executive',
    us_salary_min: 50000, us_salary_max: 85000, us_salary_avg: 65000,
    offshore_salary_min: 8000, offshore_salary_max: 18000, offshore_salary_avg: 12000,
    savings_percentage: 82,
    demand_level: 'medium',
    skills_required: ['Calendar Management', 'Communication', 'Organization', 'G Suite'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'IN', 'PK'],
    is_featured: true, sort_order: 16,
    description_en: 'Remote executive assistants providing top-level administrative support.',
    description_es: 'Asistentes ejecutivos remotos proporcionando soporte administrativo de alto nivel.',
  },
  {
    slug: 'customer-support-rep',
    title_en: 'Customer Support Representative',
    title_es: 'Representante de Soporte al Cliente',
    category: 'customer_service',
    us_salary_min: 35000, us_salary_max: 55000, us_salary_avg: 45000,
    offshore_salary_min: 6000, offshore_salary_max: 14000, offshore_salary_avg: 10000,
    savings_percentage: 78,
    demand_level: 'medium',
    skills_required: ['CRM', 'Communication', 'Problem Solving', 'Zendesk'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'IN', 'PK'],
    is_featured: true, sort_order: 17,
    description_en: 'English-fluent support reps handling customer inquiries.',
    description_es: 'Representantes de soporte con inglés fluido atendiendo consultas de clientes.',
  },
  {
    slug: 'digital-marketing-specialist',
    title_en: 'Digital Marketing Specialist',
    title_es: 'Especialista en Marketing Digital',
    category: 'marketing',
    us_salary_min: 55000, us_salary_max: 95000, us_salary_avg: 72000,
    offshore_salary_min: 10000, offshore_salary_max: 24000, offshore_salary_avg: 16000,
    savings_percentage: 78,
    demand_level: 'medium',
    skills_required: ['SEO', 'Google Ads', 'Social Media', 'Analytics', 'Content'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'PL', 'UA', 'IN', 'BR', 'AR'],
    is_featured: true, sort_order: 18,
    description_en: 'Growth-focused marketers driving digital acquisition.',
    description_es: 'Especialistas en marketing enfocados en crecimiento y adquisición digital.',
  },
  {
    slug: 'accountant',
    title_en: 'Accountant',
    title_es: 'Contador',
    category: 'finance',
    us_salary_min: 55000, us_salary_max: 90000, us_salary_avg: 70000,
    offshore_salary_min: 10000, offshore_salary_max: 22000, offshore_salary_avg: 15000,
    savings_percentage: 79,
    demand_level: 'medium',
    skills_required: ['QuickBooks', 'Excel', 'GAAP', 'Financial Reporting'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'IN', 'PK'],
    is_featured: true, sort_order: 19,
    description_en: 'Qualified accountants familiar with US GAAP standards.',
    description_es: 'Contadores calificados familiarizados con los estándares US GAAP.',
  },
  {
    slug: 'sales-development-rep',
    title_en: 'Sales Development Representative',
    title_es: 'Representante de Desarrollo de Ventas',
    category: 'sales',
    us_salary_min: 45000, us_salary_max: 75000, us_salary_avg: 58000,
    offshore_salary_min: 8000, offshore_salary_max: 18000, offshore_salary_avg: 12000,
    savings_percentage: 79,
    demand_level: 'medium',
    skills_required: ['CRM', 'Cold Calling', 'Email Outreach', 'Pipeline Management'],
    countries_available: ['CO', 'MX', 'PH', 'ZA', 'IN', 'PK'],
    is_featured: true, sort_order: 20,
    description_en: 'Outbound sales specialists generating qualified leads.',
    description_es: 'Especialistas en ventas outbound generando leads calificados.',
  },
];

export function getRoleBySlug(slug: string) {
  return SALARY_DATA.find((r) => r.slug === slug);
}

export function getRolesByCategory(category: string) {
  return SALARY_DATA.filter((r) => r.category === category);
}

export function getFeaturedRoles() {
  return SALARY_DATA.filter((r) => r.is_featured).sort((a, b) => a.sort_order - b.sort_order);
}

export function getCategories() {
  return Array.from(new Set(SALARY_DATA.map((r) => r.category)));
}
